### ISSUE TITLE
Create a settings panel

### ISSUE THREAD

**Issue by zeeldadhaniya1895** [MSTC-DA-IICT/Hacktoberfest24-Drawing-Canvas-React#12]
Task: Create a settings panel where users can switch between different layout options (e.g., grid vs. list view) using a simple toggle or dropdown. Implement a layout toggle where users can switch between grid and list views, and the application reflects the selected layout.

**Comment by Vishrut99** [comment]
I want to solve this can you please assign me ??

**Comment by atik-7866** [comment]
Hey @zeeldadhaniya1895  Pls do assign this issue to me. I got the idea and implemented somewhat .
It would probably look like
![image](https://github.com/user-attachments/assets/9db10499-c644-4a21-bc79-db01fa2bc089)

**Comment by OmPatel1511** [comment]
I want to solve this, please assign this to me

**Comment by shyamsaktawat** [comment]
Hi @zeeldadhaniya1895,

I’m interested in working on this issue and would love to contribute by creating the settings panel with the layout toggle functionality. I have a clear understanding of how to implement the toggle between grid and list views and ensure the application reflects the user's selected layout.

Could you please assign this task to me?

Looking forward to your confirmation

**Comment by zeeldadhaniya1895** [comment]
@shyamsaktawat I am assigning this issue to you
