### ISSUE TITLE
Undo/Redo Functionality: Easily revert or restore previous drawing actions.

### ISSUE THREAD

**Issue by Aayushgoyal00** [MSTC-DA-IICT/Hacktoberfest24-Drawing-Canvas-React#3]
Implement undo and redo functionality by storing a history of drawing strokes and allowing users to move back or forward through the drawing history.

**Comment by kavya020805** [comment]
Please assign the issue to me.

**Comment by atik-7866** [comment]
Hello @Aayushgoyal00 ,Please do assign me this issue i wanna work on it.
Idea of implementation:
I will be creating 2 states using usestate hook for the history and redo functionality .
For storing the state we have to use stack as we want the most recent thing back.And when stroke is complete i will clear the stack.

**Comment by kavya020805** [comment]
@Aayushgoyal00 
I have implemented the undo/redo functionality, which works perfectly. Additionally, I have added a feature that allows you to recover the previous drawing even after clearing the canvas using the 'Clear Canvas' button.
Here's a preview.
https://github.com/user-attachments/assets/f7fa2bd2-a716-49d0-89b7-a4b529aafe21

**Comment by Aayushgoyal00** [comment]
> Please assign the issue to me.

you are already assigned to issue #7 so do that first

**Comment by 202201255** [comment]
@Aayushgoyal00 
Please assign the issue to me.
I will implement a global keyboard event listener using window.addEventListener('keydown') to capture Ctrl + Z for undo and Ctrl + Y for redo actions. The listener will trigger the corresponding functions and prevent the default browser behavior when these shortcuts are pressed.

**Comment by rathodjay19** [comment]
@Aayushgoyal00 
Please assign the issue to me.
I will implement a global keyboard event listener using window.addEventListener('keydown') to capture Ctrl + Z for undo and Ctrl + Y for redo actions. The listener will trigger the corresponding functions and prevent the default browser behavior when these shortcuts are pressed.

**Comment by ManojDhundhalva** [comment]
@rathodjay19, This issue has been assigned to you. You can now continue working on your task.

**Comment by Aayushgoyal00** [comment]
@rathodjay19 
what's the current status for this issue

**Comment by rathodjay19** [comment]
@Aayushgoyal00 
hey, since i'm quite busy 
Please pass this issue to other people....

**Comment by zeeldadhaniya1895** [comment]
well done kavya
