### ISSUE TITLE
Multi-Tab Synchronization: Drawings persist and sync across multiple tabs using LocalStorage

### ISSUE THREAD

**Issue by Aayushgoyal00** [MSTC-DA-IICT/Hacktoberfest24-Drawing-Canvas-React#4]
Use localStorage and the storage event to synchronize drawing actions across multiple open browser tabs.

**Comment by kavya020805** [comment]
@Aayushgoyal00 
Please assign this issue to me.

**Comment by shyamsaktawat** [comment]
Hi @Aayushgoyal00,

I’m excited about the opportunity to work on this issue! I have experience working with LocalStorage and browser events, and I’d like to contribute by implementing real-time multi-tab synchronization for drawing actions.

Implementation Plan:
LocalStorage for Persistence: I’ll store drawing data in LocalStorage so it persists across multiple tabs even after they are closed and reopened.
Synchronization using the storage event: I’ll utilize the storage event to detect changes in LocalStorage across different tabs. This will allow immediate synchronization of drawings in real-time across all open tabs.
Optimizing for Performance: To avoid excessive event firing, I will implement a debouncing mechanism to ensure efficient updates without overloading the browser.
Compatibility and Responsiveness: I’ll ensure this synchronization works seamlessly across different browsers and devices, with attention to maintaining responsiveness and user experience.
Could you please assign this task to me? Looking forward to contributing and helping improve the project!

**Comment by zeeldadhaniya1895** [comment]
@shyamsaktawat I have already assigned you an issue #12 so first try to solve that

**Comment by zeeldadhaniya1895** [comment]
@atik-7866 I am assigning you this issue do your best.
