### ISSUE TITLE
Export as Image: Export the current drawing as a PNG or JPG image.

### ISSUE THREAD

**Issue by Aayushgoyal00** [MSTC-DA-IICT/Hacktoberfest24-Drawing-Canvas-React#6]
Allow users to export their current drawing as an image file by converting the canvas to a downloadable PNG or JPG format

**Comment by kavya020805** [comment]
@Aayushgoyal00 
Please assign the issue to me.

**Comment by zeeldadhaniya1895** [comment]
@kavya020805, I am assigning this issue to you

**Comment by zeeldadhaniya1895** [comment]
Hi @kavya020805 ,

Great work on the pull request! One small enhancement I'd like to suggest is to add functionality for image downloads in different formats (like PNG, JPEG, and PDF). This will make the feature more versatile.

Can you please update your PR to include this?

Thanks!

**Comment by zeeldadhaniya1895** [comment]
Hi @kavya020805,

Great work on the pull request! One small enhancement I'd like to suggest is to add functionality for image downloads in different formats (like PNG, JPEG, and PDF). This will make the feature more versatile.

Can you please update your PR to include this?

Thanks!

**Comment by kavya020805** [comment]
@zeeldadhaniya1895 
Okay 👍

**Comment by zeeldadhaniya1895** [comment]
@kavya020805 well done.

**Comment by Monson2002** [comment]
@zeeldadhaniya1895 and @kavya020805 I am getting this error while trying to set up the project locally
![Screenshot 2024-10-02 142120](https://github.com/user-attachments/assets/97cad418-6368-424a-93f5-3fa73e77043a)
Is there an issue from my side?

**Comment by kavya020805** [comment]
@Monson2002 
You need to install a third party package for convert file to pdf. just run this cmd
npm install jspdf

**Comment by Monson2002** [comment]
> @Monson2002 You need to install a third party package for convert file to pdf. just run this cmd npm install jspdf

Yeah this solves the issue , I g you should raise an issue for the same (in the issues tab), as this could become repetitive if one doesn't mention the imports in package.json (on every pull one is forced to do npm I jspdf)

**Comment by kavya020805** [comment]
@Monson2002 In my next pull request i will fix that issue
