### ISSUE TITLE
Shape Drawing: Draw predefined shapes (rectangles, circles, lines) on the canvas.

### ISSUE THREAD

**Issue by Aayushgoyal00** [MSTC-DA-IICT/Hacktoberfest24-Drawing-Canvas-React#7]
Implement additional drawing tools for predefined shapes such as rectangles, circles, and straight lines.

**Comment by atik-7866** [comment]
Hello @Aayushgoyal00 @zeeldadhaniya1895 I wanna work on this issue.
Am not aware of how will i do it but i wanna give it a try and learn from it.

**Comment by Aayushgoyal00** [comment]
ok @atik-7866 ,I am assigning this issue to you

**Comment by kavya020805** [comment]
@zeeldadhaniya1895 
Can you please assign this to me.

**Comment by zeeldadhaniya1895** [comment]
@kavya020805 I am assigning this issue to you ,try to give your best.
