### ISSUE TITLE
Offline Mode: Works fully offline, with no need for backend or internet connection

### ISSUE THREAD

**Issue by Aayushgoyal00** [MSTC-DA-IICT/Hacktoberfest24-Drawing-Canvas-React#9]
Issue Description: Ensure that all functionalities (drawing, saving, loading, etc.) work completely offline using browser storage mechanisms.

**Comment by Monson2002** [comment]
@Aayushgoyal00  and @zeeldadhaniya1895 could someone please host this on a server(Netlify, cloud etc) so that one can test this feature

**Comment by Aayushgoyal00** [comment]
@Monson2002 it is now deployed on netlify and the live link is present in the readme file of the repo.

**Comment by vi1js** [comment]
can you please assign this task to me i will try my best to solve this issue
